// File generated by Antigravity AI for Firebase configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xemFr_61DoFy1jLVdhJcC45-ux70r6g',
    appId: '1:297622210008:web:afcdf5bc356f21f10f5ead',
    messagingSenderId: '297622210008',
    projectId: 'mapo-8d306',
    authDomain: 'mapo-8d306.firebaseapp.com',
    storageBucket: 'mapo-8d306.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xemFr_61DoFy1jLVdhJcC45-ux70r6g',
    appId: '1:297622210008:android:afcdf5bc356f21f10f5ead',
    messagingSenderId: '297622210008',
    projectId: 'mapo-8d306',
    storageBucket: 'mapo-8d306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xemFr_61DoFy1jLVdhJcC45-ux70r6g',
    appId: '1:297622210008:ios:afcdf5bc356f21f10f5ead',
    messagingSenderId: '297622210008',
    projectId: 'mapo-8d306',
    storageBucket: 'mapo-8d306.firebasestorage.app',
  );
}
